Shop.Web/Areas/Admin/Controllers/HomeController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Features.OrderEntities.Order.Requests.Queries;

namespace Shop.Web.Areas.Admin.Controllers
{
    public class HomeController : AdminBaseController
    {
        private readonly IMediator _mediator;

        public HomeController(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IActionResult> Index()
        {
            ViewData["ResultOrder"] = await _mediator.Send(new GetResaultOrderRequest() { });
            return View();
        }
    }
}

Shop.Web/Areas/User/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Shop.Web.Areas.User.Controllers
{
    public class HomeController : UserBaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Shop.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Contracts.Infrastructure.IServices;

namespace Shop.Web.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ISiteSettingService _siteSettingService;

        public HomeController(ISiteSettingService siteSettingService)
        {
            _siteSettingService = siteSettingService;
        }
        public async Task<IActionResult> Index()
        {
            ViewData["LastProducts"] = await _siteSettingService.LastProducts();
            return View();
        }
        public IActionResult Error()
        { 
            return View();
        }
    }
}

Shop.Web/ViewComponents/SiteViewComponent.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Contracts.Infrastructure.IServices;
using Shop.Application.DTOs.Admin.Product;
using Shop.Application.DTOs.Admin.SiteSetting.Slider;
using Shop.Application.Extentions;
using Shop.Application.Features.Account.Users.Requests.Queries;
using Shop.Application.Features.OrderEntities.Order.Requests.Queries;
using Shop.Application.Features.Product.Category.Requests.Queries;
using Shop.Application.Features.Product.Comment.Requests.Queries;
using Shop.Domain.Models.Account;
using Shop.Infrastructure.Services;

namespace Shop.Web.ViewComponents
{
    #region Header
    public class SiteHeaderViewComponent : ViewComponent
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public SiteHeaderViewComponent(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }
       
        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _mediator.Send(new GetUserByPhoneNumRequest() { PhoneNumber = User.Identity.Name });
                var map = _mapper.Map<User>(user);
                
                ViewBag.User = map;
                ViewBag.Order = await _mediator.Send(new GetUserBasketByUserIdRequest() { UserId = User.GetUserId() });
                ViewBag.UserCompare = await _mediator.Send(new GetUserComparesRequest() { UserId = User.GetUserId() });
                ViewBag.FavoritCount = await _mediator.Send(new UserFavoritCountRequest() { UserId = User.GetUserId() });

            }
            return View("SiteHeader");
        }
    }
    #endregion

    #region Footer
    public class SiteFooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("SiteFooter");
        }
    }
    #endregion

    #region Slider
    public class SiteSliderViewComponent : ViewComponent
    {
        private readonly ISiteSettingService _siteSettingService;

        public SiteSliderViewComponent(ISiteSettingService siteSettingService)
        {
            _siteSettingService = siteSettingService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var filterslider = new FilterSlidersDto
            {
                TakeEntity = 5
            };
            var data = await _siteSettingService.FilterSliders(filterslider);
            return View("SiteSlider",data);
        }
    }
    #endregion
    
    #region popular Category
    public class PopularCategoryViewComponent : ViewComponent
    {
        private readonly IMediator _mediator;
        public PopularCategoryViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var filterCategory = new FilterCategoryDto();
            filterCategory.TakeEntity = 2;
            var data =await _mediator.Send(new FilterCategoryRequest() { FilterCategoryDto=filterCategory});
            return View("PopularCategory", data);
        }
    }
    #endregion

    #region  Category
    public class NavbarCategoryViewComponent : ViewComponent
    {
        private readonly IMediator _mediator;
        public NavbarCategoryViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var filterCategory = new FilterCategoryDto();
            var data = await _mediator.Send(new FilterCategoryRequest() { FilterCategoryDto = filterCategory });
            return View("NavbarCategory", data);
        }
    }
    #endregion

    #region  AllProductInSlider
    public class AllProductInSliderViewComponent : ViewComponent
    {
        private readonly ISiteSettingService _siteSettingService;

        public AllProductInSliderViewComponent(ISiteSettingService siteSettingService)
        {
            _siteSettingService = siteSettingService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
        var data =await _siteSettingService.ShowAllProductsInSlider();
            return View("AllProductInSlider", data);
        }
    }
    #endregion

    #region  AllProductInCategoryWomen
    public class AllProductInCategoryWomenViewComponent : ViewComponent
    {
        private readonly ISiteSettingService _siteSettingService;

        public AllProductInCategoryWomenViewComponent(ISiteSettingService siteSettingService)
        {
            _siteSettingService = siteSettingService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var data = await _siteSettingService.ShowAllProductsInCategory("Women");
            return View("AllProductInCategoryWomen", data);
        }
    }
    #endregion

    #region  AllProductInCategoryMen
    public class AllProductInCategoryMenViewComponent : ViewComponent
    {
        private readonly ISiteSettingService _siteSettingService;

        public AllProductInCategoryMenViewComponent(ISiteSettingService siteSettingService)
        {
            _siteSettingService = siteSettingService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var data = await _siteSettingService.ShowAllProductsInCategory("Men");
            return View("AllProductInCategoryMen", data);
        }
    }
    #endregion

    #region All-productInCategoryPc - home
    public class ProductCommentsViewComponent : ViewComponent
    {
        #region constractor
      
        private readonly IMediator _mediator;

        public ProductCommentsViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }
        #endregion

        public async Task<IViewComponentResult> InvokeAsync(long productId)
        {

            var data = await _mediator.Send(new GetAllCommentsByIdRequest() { ProductId = productId });

            return View("ProductComments", data);
        }
    }
    #endregion
}

Shop.Web/Views/Home/Index.cshtml
@using Shop.Application.DTOs.Site;
@{
    ViewData["Title"] = "خانه";
    var lastProducts = (List<ProductItemDto>)ViewData["LastProducts"];
}

<div class="intro-slider-container">
    @await Component.InvokeAsync("SiteSlider");
</div><!-- End .intro-slider-container -->
<div class="container">
</div>
<div class="pt-2 pb-3">
    <div class="container">
        <div class="row">
            @await Component.InvokeAsync("PopularCategory")
            <hr class="mt-0 mb-0">
        </div>
    </div>
</div>


<div class="mb-5"></div>


<div class="container">
    <div class="heading heading-center mb-3">
        <h2 class="title text-center">محصولات برتر</h2><!-- End .title -->

        <ul class="nav nav-pills justify-content-center" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="trending-all-link" data-toggle="tab" href="#trending-all-tab"
                   role="tab" aria-controls="trending-all-tab" aria-selected="true">همه</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="trending-women-link" data-toggle="tab" href="#trending-women-tab"
                   role="tab" aria-controls="trending-women-tab" aria-selected="false">زنانه</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="trending-men-link" data-toggle="tab" href="#trending-men-tab"
                   role="tab" aria-controls="trending-men-tab" aria-selected="false">مردانه</a>
            </li>
        </ul>
    </div><!-- End .heading -->

    <div class="tab-content tab-content-carousel">
        <div class="tab-pane p-0 fade show active" id="trending-all-tab" role="tabpanel"
             aria-labelledby="trending-all-link">
            <div class="owl-carousel owl-simple carousel-equal-height carousel-with-shadow"
                 data-toggle="owl" data-owl-options='{
                                "nav": false,
                                "dots": true,
                                "margin": 20,
                                "loop": false,
                                "rtl": true,
                            "responsive": {
                                    "0": {
                                        "items":2
                                    },
                                    "480": {
                                        "items":2
                                    },
                                    "768": {
                                        "items":3
                                    },
                                    "992": {
                                        "items":4
                                    },
                                    "1200": {
                                        "items":4,
                                        "nav": true,
                                        "dots": false
                                    }
                                }
                            }'>
                @await Component.InvokeAsync("AllProductInSlider")

            </div><!-- End .owl-carousel -->
        </div><!-- .End .tab-pane -->
        <div class="tab-pane p-0 fade" id="trending-women-tab" role="tabpanel"
             aria-labelledby="trending-women-link">
            <div class="owl-carousel owl-simple carousel-equal-height carousel-with-shadow"
                 data-toggle="owl" data-owl-options='{
                                "nav": false,
                                "dots": true,
                                "margin": 20,
                                "loop": false,
                                "rtl": true,
                            "responsive": {
                                    "0": {
                                        "items":0
                                    },
                                    "480": {
                                        "items":2
                                    },
                                    "768": {
                                        "items":3
                                    },
                                    "992": {
                                        "items":4
                                    },
                                    "1200": {
                                        "items":4,
                                        "nav": true,
                                        "dots": false
                                    }
                                }
                            }'>
                @await Component.InvokeAsync("AllProductInCategoryWomen")
            </div><!-- End .owl-carousel -->
        </div><!-- .End .tab-pane -->

        <div class="tab-pane p-0 fade" id="trending-men-tab" role="tabpanel"
             aria-labelledby="trending-men-link">
            <div class="owl-carousel owl-simple carousel-equal-height carousel-with-shadow"
                 data-toggle="owl" data-owl-options='{
                                "nav": false,
                                "dots": true,
                                "margin": 20,
                                "loop": false,
                                "rtl": true,
                            "responsive": {
                                    "0": {
                                        "items":0
                                    },
                                    "480": {
                                        "items":2
                                    },
                                    "768": {
                                        "items":3
                                    },
                                    "992": {
                                        "items":4
                                    },
                                    "1200": {
                                        "items":4,
                                        "nav": true,
                                        "dots": false
                                    }
                                }
                            }'>
                @await Component.InvokeAsync("AllProductInCategoryMen")
            </div><!-- End .owl-carousel -->
        </div><!-- .End .tab-pane -->
    </div><!-- End .tab-content -->
</div><!-- End .container -->

<div class="mb-5"></div><!-- End .mb-5 -->

<div class="pt-4 pb-3" style="background-color: #222;">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-3 col-sm-6">
                <div class="icon-box text-center">
                    <span class="icon-box-icon">
                        <i class="icon-truck"></i>
                    </span>
                    <div class="icon-box-content">
                        <h3 class="icon-box-title">پرداخت و ارسال</h3><!-- End .icon-box-title -->
                        <p class="text-center">ارسال رایگان برای سفارشات بالای 50 هزار تومان</p>
                    </div><!-- End .icon-box-content -->
                </div><!-- End .icon-box -->
            </div><!-- End .col-lg-3 col-sm-6 -->

            <div class="col-lg-3 col-sm-6">
                <div class="icon-box text-center">
                    <span class="icon-box-icon">
                        <i class="icon-rotate-left"></i>
                    </span>
                    <div class="icon-box-content">
                        <h3 class="icon-box-title">مرجوع کردن سفارشات</h3><!-- End .icon-box-title -->
                        <p class="text-center">گارانتی بازگرداندن وجه به صورت کامل</p>
                    </div><!-- End .icon-box-content -->
                </div><!-- End .icon-box -->
            </div><!-- End .col-lg-3 col-sm-6 -->

            <div class="col-lg-3 col-sm-6">
                <div class="icon-box text-center">
                    <span class="icon-box-icon">
                        <i class="icon-unlock"></i>
                    </span>
                    <div class="icon-box-content">
                        <h3 class="icon-box-title">پرداخت امن</h3><!-- End .icon-box-title -->
                        <p class="text-center">100% پرداخت امن</p>
                    </div><!-- End .icon-box-content -->
                </div><!-- End .icon-box -->
            </div><!-- End .col-lg-3 col-sm-6 -->

            <div class="col-lg-3 col-sm-6">
                <div class="icon-box text-center">
                    <span class="icon-box-icon">
                        <i class="icon-headphones"></i>
                    </span>
                    <div class="icon-box-content">
                        <h3 class="icon-box-title">پشتیبانی حرفه ای</h3><!-- End .icon-box-title -->
                        <p class="text-center">پشتبانی آنلاین به صورت 7روز هفته/24ساعته</p>
                    </div><!-- End .icon-box-content -->
                </div><!-- End .icon-box -->
            </div><!-- End .col-lg-3 col-sm-6 -->
        </div><!-- End .row -->
    </div><!-- End .container -->
</div><!-- End .bg-light pt-2 pb-2 -->

<div class="mb-6"></div><!-- End .mb-5 -->

<div class="container">
    <h2 class="title text-center mb-4">آخرین محصولات</h2><!-- End .title text-center -->

    <div class="products">
        <div class="row justify-content-center">
           
            <partial name="_NewProductBox" model="@lastProducts"/>

        </div><!-- End .row -->
    </div><!-- End .products -->

    <div class="more-container text-center mt-2">
        <a href="#" class="btn btn-outline-dark-2 btn-more"><span>نمایش بیشتر</span></a>
    </div><!-- End .more-container -->
</div><!-- End .container -->