Shop.Web/Controllers/ProductController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.DTOs.Admin.Product;
using Shop.Application.DTOs.Site;
using Shop.Application.Extentions;
using Shop.Application.Features.OrderEntities.Order.Requests.Commands;
using Shop.Application.Features.Product.Category.Requests.Queries;
using Shop.Application.Features.Product.Comment.Requests.Commands;
using Shop.Application.Features.Product.Product.Requests.Queries;
using Shop.Domain.Enums;
using Shop.Web.Models.VM.Site.Products;

namespace Shop.Web.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;
        #region constractor
        public ProductController(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }
        #endregion


        #region products
        [HttpGet("products")]
        public async Task<IActionResult> Products(FilterProductsDto filter)
        {

            filter.TakeEntity = 12;
            filter.ProductBox = ProductBox.ItemBoxInSite;

            ViewData["Categories"] = await _mediator.Send(new GetAllCategoriesRequest());
            var FinalFilter = await _mediator.Send(new FilterProductsRequest() { filterProductsDto = filter });
            return View(FinalFilter);
        }
        #endregion

        #region show-product
        [HttpGet("showDetail/{productId}")]
        public async Task<IActionResult> ProductDetail(long productId)
        {
            var data = await _mediator.Send(new GetProductDetailRequest() { ProductId = productId });
            if (data == null)
            {
                return NotFound();
            }

            TempData["relatedProduct"] = await _mediator.Send(new GetRelatedProductRequest() { CategoryName = data.Category.UrlName, ProductId = productId });

            return View(_mapper.Map<ProductDetailVM>(data));
        }
        #endregion

        #region create-product-comment
        [HttpPost("add-comment"), ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProductComment(CreateProductCommentVM createProductComment)
        {
            var comment = _mapper.Map<CreateProductCommentDto>(createProductComment);
            if (!string.IsNullOrEmpty(comment.Text))
            {
                var commend = new CreateProductCommentCommandRequest() { CreateProductCommentDto = comment, UserId = User.GetUserId() };
                var response = await _mediator.Send(commend);
                switch (response)
                {
                    case CreateProductCommentResult.CheckUser:
                        TempData[WarningMessage] = "کاربر مورد نظر یافت نشد";
                        break;
                    case CreateProductCommentResult.CheckProduct:
                        TempData[WarningMessage] = "محصولی یافت نشد";
                        break;
                    case CreateProductCommentResult.Success:
                        TempData[SuccessMessage] = "نظر شما با موفقیت ثبت شد";
                        return RedirectToAction("ProductDetail", new { productId = comment.ProductId });

                }
            }

            TempData[ErrorMessage] = "لطفا نظر خود را وارد نمایید";
            return RedirectToAction("ProductDetail", new { productId = createProductComment.ProductId });

        }
        #endregion

        #region buy-product

        [Authorize]
        public async Task<IActionResult> BuyProduct(long productId)
        {
            var command=new AddOrderCommandRequest() { ProductId = productId ,UserId=User.GetUserId() };
            var response=await _mediator.Send(command);
            return Redirect("/User/Basket/" + response);
        }
        #endregion
    }
}

Shop.Web/ViewComponents/SiteViewComponent.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Contracts.Infrastructure.IServices;
using Shop.Application.DTOs.Admin.Product;
using Shop.Application.DTOs.Admin.SiteSetting.Slider;
using Shop.Application.Extentions;
using Shop.Application.Features.Account.Users.Requests.Queries;
using Shop.Application.Features.OrderEntities.Order.Requests.Queries;
using Shop.Application.Features.Product.Category.Requests.Queries;
using Shop.Application.Features.Product.Comment.Requests.Queries;
using Shop.Domain.Models.Account;
using Shop.Infrastructure.Services;

namespace Shop.Web.ViewComponents
{
    #region Header
    public class SiteHeaderViewComponent : ViewComponent
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public SiteHeaderViewComponent(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }
       
        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _mediator.Send(new GetUserByPhoneNumRequest() { PhoneNumber = User.Identity.Name });
                var map = _mapper.Map<User>(user);
                
                ViewBag.User = map;
                ViewBag.Order = await _mediator.Send(new GetUserBasketByUserIdRequest() { UserId = User.GetUserId() });
                ViewBag.UserCompare = await _mediator.Send(new GetUserComparesRequest() { UserId = User.GetUserId() });
                ViewBag.FavoritCount = await _mediator.Send(new UserFavoritCountRequest() { UserId = User.GetUserId() });

            }
            return View("SiteHeader");
        }
    }
    #endregion

    #region Footer
    public class SiteFooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("SiteFooter");
        }
    }
    #endregion

    #region Slider
    public class SiteSliderViewComponent : ViewComponent
    {
        private readonly ISiteSettingService _siteSettingService;

        public SiteSliderViewComponent(ISiteSettingService siteSettingService)
        {
            _siteSettingService = siteSettingService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var filterslider = new FilterSlidersDto
            {
                TakeEntity = 5
            };
            var data = await _siteSettingService.FilterSliders(filterslider);
            return View("SiteSlider",data);
        }
    }
    #endregion
    
    #region popular Category
    public class PopularCategoryViewComponent : ViewComponent
    {
        private readonly IMediator _mediator;
        public PopularCategoryViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var filterCategory = new FilterCategoryDto();
            filterCategory.TakeEntity = 2;
            var data =await _mediator.Send(new FilterCategoryRequest() { FilterCategoryDto=filterCategory});
            return View("PopularCategory", data);
        }
    }
    #endregion

    #region  Category
    public class NavbarCategoryViewComponent : ViewComponent
    {
        private readonly IMediator _mediator;
        public NavbarCategoryViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var filterCategory = new FilterCategoryDto();
            var data = await _mediator.Send(new FilterCategoryRequest() { FilterCategoryDto = filterCategory });
            return View("NavbarCategory", data);
        }
    }
    #endregion

    #region  AllProductInSlider
    public class AllProductInSliderViewComponent : ViewComponent
    {
        private readonly ISiteSettingService _siteSettingService;

        public AllProductInSliderViewComponent(ISiteSettingService siteSettingService)
        {
            _siteSettingService = siteSettingService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
        var data =await _siteSettingService.ShowAllProductsInSlider();
            return View("AllProductInSlider", data);
        }
    }
    #endregion

    #region  AllProductInCategoryWomen
    public class AllProductInCategoryWomenViewComponent : ViewComponent
    {
        private readonly ISiteSettingService _siteSettingService;

        public AllProductInCategoryWomenViewComponent(ISiteSettingService siteSettingService)
        {
            _siteSettingService = siteSettingService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var data = await _siteSettingService.ShowAllProductsInCategory("Women");
            return View("AllProductInCategoryWomen", data);
        }
    }
    #endregion

    #region  AllProductInCategoryMen
    public class AllProductInCategoryMenViewComponent : ViewComponent
    {
        private readonly ISiteSettingService _siteSettingService;

        public AllProductInCategoryMenViewComponent(ISiteSettingService siteSettingService)
        {
            _siteSettingService = siteSettingService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var data = await _siteSettingService.ShowAllProductsInCategory("Men");
            return View("AllProductInCategoryMen", data);
        }
    }
    #endregion

    #region All-productInCategoryPc - home
    public class ProductCommentsViewComponent : ViewComponent
    {
        #region constractor
      
        private readonly IMediator _mediator;

        public ProductCommentsViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }
        #endregion

        public async Task<IViewComponentResult> InvokeAsync(long productId)
        {

            var data = await _mediator.Send(new GetAllCommentsByIdRequest() { ProductId = productId });

            return View("ProductComments", data);
        }
    }
    #endregion
}

Shop.Web/Views/Shared/_CaptchaInput.cshtml
@using Shop.Web.Models.VM.Site;
@model Recaptcha

<input type="hidden" asp-for="Token" id="captchaInput" />

Shop.Web/Views/Shared/_CaptchaScripts.cshtml
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration
<script src="https://www.google.com/recaptcha/api.js?render=@Configuration["googleReCaptcha:SiteKey"]"></script>
<script>
    grecaptcha.ready(function() {
        window.grecaptcha.execute('@Configuration["googleReCaptcha:SiteKey"]', { action: 'home' }).then(function (token) {
            $("#captchaInput").val(token);
        });
    });
</script>

Shop.Web/Views/Shared/_HeaderPartial.cshtml
  <!-- Plugins CSS File -->
<link rel="stylesheet" href="/css/bootstrap.min.css">
<link rel="stylesheet" href="/css/bootstrap-rtl.min.css">
<link rel="stylesheet" href="/css/plugins/owl-carousel/owl.carousel.css">
<link rel="stylesheet" href="/css/plugins/magnific-popup/magnific-popup.css">
<link rel="stylesheet" href="/css/plugins/jquery.countdown.css">
<!-- Main CSS File -->
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/notifications.css">
<link rel="stylesheet" href="/css/skins/skin-demo-6.css">
<link rel="stylesheet" href="/css/demos/demo-6.css">
<link rel="stylesheet" href="/vendor/line-awesome/line-awesome/line-awesome/css/line-awesome.min.css">
<link href="/userPanel/css/account.css" rel="stylesheet" />
<link href="/userPanel/css/style.css" rel="stylesheet" />

Shop.Web/Views/Shared/_JsPartials.cshtml
<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.bundle.min.js"></script>
<script src="/js/jquery.hoverIntent.min.js"></script>
<script src="/js/jquery.waypoints.min.js"></script>
<script src="/js/superfish.min.js"></script>
<script src="/js/owl.carousel.min.js"></script>
<script src="/js/bootstrap-input-spinner.js"></script>
<script src="/js/jquery.plugin.min.js"></script>
<script src="/js/jquery.magnific-popup.min.js"></script>
<script src="/js/jquery.countdown.min.js"></script>
<!-- Main JS File -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7/dist/sweetalert2.all.min.js"></script>
<script src="/js/main.js"></script>
<script src="/js/demos/demo-6.js"></script>
<script src="/js/custom.js"></script>
<script src="/js/demos/notifications.js"></script>

Shop.Web/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <title>@ViewData["Title"]</title>
    <partial name="_HeaderPartial" />
    <partial name="_MetaTagHeader" />
    <!-- Favicon -->
    @RenderSection("Styles",false)
</head>

<body>
    <div class="page-wrapper">
        @await Component.InvokeAsync("SiteHeader")

        <main class="main">
           @RenderBody()
        </main><!-- End .main -->

        @await Component.InvokeAsync("SiteFooter")
    </div><!-- End .page-wrapper -->
    <button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>

    <partial name="_Mobile" />

    <partial name="_JsPartials" />
    @RenderSection("Scripts",false)
    <partial name="_Message" />
</body>

</html>

Shop.Web/Views/Shared/_MetaTagHeader.cshtml
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="apple-touch-icon" sizes="180x180" href="/images/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/images/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/images/icons/favicon-16x16.png">
<link rel="manifest" href="/images/icons/site.webmanifest">
<link rel="mask-icon" href="/images/icons/safari-pinned-tab.html" color="#666666">
<link rel="shortcut icon" href="/images/icons/favicon.ico">
<meta name="keywords" content="HTML5 Template">
<meta name="description" content="Molla - Bootstrap eCommerce Template">
<meta name="author" content="p-themes">
<meta name="apple-mobile-web-app-title" content="Molla">
<meta name="application-name" content="Molla">
<meta name="msapplication-TileColor" content="#cc9966">
<meta name="msapplication-config" content="/images/icons/browserconfig.html">
<meta name="theme-color" content="#ffffff">

Shop.Web/Views/Shared/_NewProductBox.cshtml
@using Shop.Application.Utils;
@model List<Shop.Application.DTOs.Site.ProductItemDto>

@if (Model !=null && Model.Any())
{
    @foreach (var product in Model)
    {
        <div class="col-6 col-md-4 col-lg-3">
            <div class="product product-7 text-center">
                <figure class="product-media">
                    <a asp-area="" asp-controller="Product"
                       asp-action="ProductDetail" asp-route-productId="@product.ProductId">
                        <img src="@(PathExtensions.ProductOrgin+ product.ProductImageName)" alt="تصویر محصول" class="product-image">
                    </a>

                    <div class="product-action-vertical">
                        <a asp-area="User" asp-controller="Account" asp-action="AddUserFavorit" asp-route-productId="@product.ProductId" class="btn-product-icon btn-wishlist btn-expandable">
                            <span>
                                افزودن به
                                لیست علاقه مندی
                            </span>
                        </a>
                    </div><!-- End .product-action-vertical -->

                    <div class="product-action">
                        <a asp-controller="Product" asp-action="BuyProduct"
                           asp-route-productId="@product.ProductId" class="btn-product btn-cart"><span>افزودن به سبد خرید</span></a>
                    </div><!-- End .product-action -->
                </figure><!-- End .product-media -->

                <div class="product-body">
                    <div class="product-cat text-center">
                        <a asp-controller="Product" asp-action="Products" asp-route-FilterByCategory="@product.Category.UrlName">@product.Category.Title</a>
                    </div><!-- End .product-cat -->
                    <h3 class="product-title text-center">
                        <a asp-area="" asp-controller="Product"
                           asp-action="ProductDetail" asp-route-productId="@product.ProductId">@product.ProductName</a>
                    </h3>
                    <!-- End .product-title -->
                    <div class="product-price">
                        @product.Price.ToString("#,0 تومان")
                    </div>
                    <div>
                        <span class="ratings-text"> @product.CommentCount دیدگاه</span>
                    </div>
                </div>
            </div>
        </div>

        <!-- End .col-sm-6 col-md-4 col-lg-3 -->
    }
}

Shop.Web/Views/Shared/_Paging.cshtml
@using Shop.Domain.Models.BaseEntities;
@model BasePaging


<nav aria-label="Page navigation example">
    <ul class="pagination">
        @if (Model.StartPage < Model.PageId)
        {
            <li class="page-item">
                <a class="page-link" onclick="FillPageId(@(Model.PageId -1))" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        }

        @for (int i = Model.StartPage; i <= Model.EndPage; i++)
        {

            <li class="page-item @(Model.PageId ==i?"active":"")"><a class="page-link" onclick="FillPageId(@i)">@i</a></li>
        }

        @if (Model.EndPage > Model.PageId)
        {

            <li class="page-item">
                <a class="page-link" onclick="FillPageId(@(Model.PageId +1))" aria-label="Previous">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        }
    </ul>
</nav>

Shop.Web/Views/Shared/_ProductBox.cshtml
@using Shop.Application.DTOs.Site
@using Shop.Application.Utils

@model ProductItemDto


<div class="product product-7 text-center">
    <figure class="product-media">
        <a asp-area="" asp-controller="Product"
           asp-action="ProductDetail" asp-route-productId="@Model.ProductId">
            <img src="@(PathExtensions.ProductOrgin+ Model.ProductImageName)" alt="تصویر محصول" class="product-image">
        </a>

        <div class="product-action-vertical">
            <a asp-area="User" asp-controller="Account" asp-action="AddUserFavorit" asp-route-productId="@Model.ProductId" class="btn-product-icon btn-wishlist btn-expandable">
                <span>
                    افزودن به
                    لیست علاقه مندی
                </span>
            </a>
        </div><!-- End .product-action-vertical -->

        <div class="product-action">
            <a asp-controller="Product" asp-action="BuyProduct"
               asp-route-productId="@Model.ProductId" class="btn-product btn-cart"><span>افزودن به سبد خرید</span></a>
        </div><!-- End .product-action -->
    </figure><!-- End .product-media -->

    <div class="product-body">
        <div class="product-cat text-center">
            <a asp-area="" asp-controller="Product" asp-action="Products" asp-route-FilterByCategory="@Model.Category.UrlName">@Model.Category.Title</a>
        </div><!-- End .product-cat -->
        <h3 class="product-title text-center">
            <a asp-area="" asp-controller="Product"
               asp-action="ProductDetail" asp-route-productId="@Model.ProductId">@Model.ProductName</a>
        </h3>
        <!-- End .product-title -->
        <div class="product-price">
            @Model.Price.ToString("#,0 تومان")
        </div>
        <div>
            <span class="ratings-text"> @Model.CommentCount دیدگاه</span>
        </div>
    </div>
</div>

Shop.Web/Views/Shared/_ValidationScripts.cshtml
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>